# Servidor
server.port=${PORT:8080}

# Base de datos (nombres exactos de tu docker-compose)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Seguridad JWT y Subida de Archivos
jwt.secret=${JWT_SECRET}
app.upload.dir=${app.upload.dir}

# L\u00EDmites Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB